# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: EnricoVentola/enricoventola.github.io

media_folder: /static/media
public_folder: /media

collections:
  - name: posts
    label: Posts
    folder: /_posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }